apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simulation-service
  namespace: monitoring
  labels:
    app: simulation-service
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: simulation-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
