apiVersion: v1
kind: Service
metadata:
  name: simulation-service
  namespace: default
  labels:
    app: simulation-service
spec:
  selector:
    app: simulation-service
  ports:
    - name: http
      port: 5002
      targetPort: 5002
      protocol: TCP
